### ISSUE TITLE
[Android] Links don't work after changing theme setting

### ISSUE THREAD

**Issue by sJJdGG** [birkir/hekla#11]
After changing theme to dark, pressing Metalinks don't open chrome, wether it's set to in-app or chrome itself.
How to reproduce:
1. install app from play store.
2. change theme settings to dark.
3. links don't work anymore.

Tested environments:
1. Android 9/ Google Pixel 1/ Release (via play store)
2. Android 6.0/ Genymotion custom/ Debug (github master branch)

React native yellowbox warning on debug mode:
```
Possible Unhandled Promise Rejection (id: 0):
Error: Invalid toolbar color '#000': Unknown color
```
Related PR: #12

**Comment by tasmo** [comment]
Because the app on Play Store is not actual it still happens. Why is there a beta program if it is not used?
