### ISSUE TITLE
Publish it on alternative stores like F-droid

### ISSUE THREAD

**Issue by kevinoliveira** [birkir/hekla#16]
First of all, Great Project!
Second, this is a open-source project, would be interesting to publish it on alternatives stores about this niche like [F-droid](https://f-droid.org/), especially because it is an open-source initiative.

 (i'm not sure if here is the best place to leave a suggestion, but i din't find another place to do it in public) 
Thanks.

**Comment by birkir** [comment]
Good idea, I am totally up for that. I know amazon has an alternative store as well.

Let me look into if I need to do something special in the codebase to make it happen.

**Comment by kevinoliveira** [comment]
it's been a long time, closing the issue
