### ISSUE TITLE
Can`t run the project

### ISSUE THREAD

**Issue by leonardo2204** [birkir/hekla#5]
Hi there, I'm trying to run the project but I'm getting this stack error:

![image](https://user-images.githubusercontent.com/1509421/43595048-1974df38-9652-11e8-90fb-402aa07a8a5e.png)
Is there any config I need to init to make it work?

Thanks!

**Comment by birkir** [comment]
Yes you are absolutely correct, you need to add the firebase config for hacker news.

The best and safest way to do this is to sign up for Firebase, generate configs for both platforms (ios and android) and modify the firebase_url to match the Hacker News API.

`./android/app/google-services.json`:
```js
{
  "project_info": {
    ...
    "firebase_url": "https://hacker-news.firebaseio.com", // change to this
    ...
  },
  ...
}
```

`./ios/Hekla/GoogleService-Info.plist`
```xml
<plist version="1.0">
<dict>
        ...

	<key>DATABASE_URL</key>
	<string>https://hacker-news.firebaseio.com</string> <!-- change to this -->

        ...
</dict>
</plist>
```

**Comment by leonardo2204** [comment]
Cool, I'll give it a try!
Thanks!
