### ISSUE TITLE
Error when pushing

### ISSUE THREAD

**Issue by leonardo2204** [birkir/hekla#6]
After pushing, I'm getting this error

yarn run v1.9.2
$ jest
 FAIL  src/utils/__tests__/age.spec.ts
  ● Test suite failed to run

    Plugin 0 specified in "/Users/leonardoferrari/rn/hekla/node_modules/babel-preset-react-native/index.js" provided an invalid property of "default" (While processing preset: "/Users/leonardoferrari/rn/hekla/node_modules/babel-preset-react-native/index.js")

      at Plugin.init (node_modules/jest-config/node_modules/babel-core/lib/transformation/plugin.js:131:13)
          at Array.map (<anonymous>)
          at Array.map (<anonymous>)

 FAIL  src/utils/__tests__/prettyNumber.spec.ts
  ● Test suite failed to run

    Plugin 0 specified in "/Users/leonardoferrari/rn/hekla/node_modules/babel-preset-react-native/index.js" provided an invalid property of "default" (While processing preset: "/Users/leonardoferrari/rn/hekla/node_modules/babel-preset-react-native/index.js")

      at Plugin.init (node_modules/jest-config/node_modules/babel-core/lib/transformation/plugin.js:131:13)
          at Array.map (<anonymous>)
          at Array.map (<anonymous>)

Test Suites: 2 failed, 2 total
Tests:       0 total
Snapshots:   0 total
Time:        1.924s
Ran all test suites.

**Comment by birkir** [comment]
One quick question. Did you use yarn or npm?

**Comment by leonardo2204** [comment]
Thanks for the response:
Here is the output when I run `jest`:
```
 FAIL  src/utils/__tests__/age.spec.ts
  ● Test suite failed to run

    Plugin 0 specified in "/Users/leonardoferrari/rn/hekla/node_modules/babel-preset-react-native/index.js" provided an invalid property of "default" (While processing preset: "/Users/leonardoferrari/rn/hekla/node_modules/babel-preset-react-native/index.js")

      at Plugin.init (node_modules/jest-config/node_modules/babel-core/lib/transformation/plugin.js:131:13)
          at Array.map (<anonymous>)
          at Array.map (<anonymous>)

 FAIL  src/utils/__tests__/prettyNumber.spec.ts
  ● Test suite failed to run

    Plugin 0 specified in "/Users/leonardoferrari/rn/hekla/node_modules/babel-preset-react-native/index.js" provided an invalid property of "default" (While processing preset: "/Users/leonardoferrari/rn/hekla/node_modules/babel-preset-react-native/index.js")

      at Plugin.init (node_modules/jest-config/node_modules/babel-core/lib/transformation/plugin.js:131:13)
          at Array.map (<anonymous>)
          at Array.map (<anonymous>)

Test Suites: 2 failed, 2 total
Tests:       0 total
Snapshots:   0 total
Time:        1.342s
Ran all test suites.
```

Thank you!

**Comment by birkir** [comment]
What node version are you using?

`node -v`

**Comment by leonardo2204** [comment]
Hey,

I'm running version 10.8.0.

Thanks


Enviado do Outlook<http://aka.ms/weboutlook>

________________________________
De: Birkir Rafn Guðjónsson <notifications@github.com>
Enviado: terça-feira, 7 de agosto de 2018 11:02
Para: birkir/hekla
Cc: Leonardo Ferrari; Author
Assunto: Re: [birkir/hekla] Error when pushing (#6)


What node version are you using?

node -v

**Comment by birkir** [comment]
This seems to be a related error: https://github.com/facebook/react-native/issues/19859

I can't reproduce it, I have another machine I can try a fresh install to reproduce, but as this is a known issue, you can try some of the steps mention in the thread and report back?

Thanks Leonardo

**Comment by leonardo2204** [comment]
Fixed it, thanks!

Gonna send you a PR :D
